
services:
  frontend:
    image: node:18-slim
    command: ./run.sh
    working_dir: /frontend
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend

  api:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    command: dotnet watch run --urls http://0.0.0.0:5001/
    working_dir: /api
    ports:
      - "5001:5001"
    volumes:
      - type: bind
        source: ./api
        target: /api
